// AI 晨报数据：2026-08-29
// 来源：桌面 AI晨报仪表盘.html + GitHub AI 趋势追踪（周榜）
const BRIEFING = [
  // ===== 模型发布/更新 =====
  { cat:"model", no:1, time:"8月29日 12:31", learn:"模型量化 Q4_K_M",
    title:"智谱开源 GLM-5.3 模型权重，主打智能体编程与网络防御",
    summary:"智谱宣布开源 GLM-5.3 模型权重，支持本地运行与个性化定制，擅长复杂编码、防御性网络安全及长程任务。该模型在 AA 综合智能指数中取得 60 分，与 Claude Fable 5、GPT-5.6 Sol 等闭源旗舰同级，并与 Kimi K3 并列开源模型第一。",
    reason:"许可条款把强制安全审查限定在百亿美元级外部模型服务，自有部署和中小团队实际不受影响，开源可用性比表面限制更宽。",
    source:"IT之家（RSS）", url:"https://www.ithome.com/" },
  { cat:"model", no:2, time:"8月29日 08:01",
    title:"腾讯混元发布 Hy4 preview：770B 总参数、1M 上下文，开源上线",
    summary:"腾讯混元发布新一代旗舰模型 Hy4 preview，总参数 770B、激活参数 49B、上下文长度 1M，现已开源并在腾讯云 TokenHub 和 OpenRouter 上线。",
    reason:"长上下文 + 开源 MoE 架构，让私有化部署与长文档处理成本显著下降。",
    source:"公众号：腾讯混元", url:"https://hunyuan.tencent.com/" },
  { cat:"model", no:3, time:"8月28日 23:04", learn:"对齐失败",
    title:"GLM-5.3 开源权重，智能体编码与网防最强",
    summary:"GLM-5.3 现已开放权重。智谱表示这是其最强大的智能体编码与网络防御模型，可供下载、运行和定制。权重已上传 Hugging Face，并发布技术博客。",
    reason:"开放权重让需要私有化部署的编码智能体与安全防御场景可以直接下载、运行和定制模型，不再受闭源 API 限制。",
    source:"X：智谱 Z.ai", url:"https://z.ai/blog/glm-5.3" },

  // ===== 产品发布/更新 =====
  { cat:"product", no:4, time:"8月29日 08:01",
    title:"Claude Code v2.1.251 发布：新增模型切换钩子与远程控制流式输出",
    summary:"Claude Code v2.1.251 新增 PreModelSwitch 和 PostModelSwitch 钩子事件，支持拦截、确认或标注模型切换；远程控制客户端现可实时流式查看前台子代理的工具调用与结果。/usage 新增消费限额条，/cost 新增按会话的提示词缓存统计行。",
    reason:"本次更新还修复了符号链接路径穿越、插件路径越界、后台会话卡死等多项安全与稳定性问题。",
    source:"Claude Code：GitHub Releases", url:"https://github.com/anthropics/claude-code/releases" },
  { cat:"product", no:5, time:"8月29日 08:01",
    title:"Databricks Genie One 新增功能：将洞察转化为行动",
    summary:"Databricks 为 Genie One 推出新功能，帮助用户将 AI 生成的洞察直接转化为实际行动。新功能聚焦于从“回答问题”到“执行任务”的延伸，使用户能在同一界面内基于分析结果触发后续操作。",
    reason:"减少来回切换工具的成本，是 AI 数据分析产品从「对话」走向「工作流」的典型方向。",
    source:"Databricks：Blog", url:"https://www.databricks.com/blog" },
  { cat:"product", no:6, time:"8月29日 08:01",
    title:"Claude for Teachers 面向学校和学区开放免费 Enterprise 版本",
    summary:"Anthropic 将 Claude for Teachers 作为免费 Enterprise 产品开放给学校和学区，提供基于学习科学的 teaching skills 及覆盖全美 50 州的学术标准连接。",
    reason:"教育场景成为大模型 ToB/ToG 落地的重点，免费策略有助于快速建立师生使用习惯。",
    source:"Claude：Blog", url:"https://www.anthropic.com/news" },
  { cat:"product", no:7, time:"8月28日 08:00", learn:"ASR 自动语音识别",
    title:"Open ASR 排行榜新增首个全球南方语言：印地语与印度英语评测集",
    summary:"Voice Arena 与 Hugging Face 合作，为 Open ASR 排行榜引入 Monsoon en-IN 和 Monsoon hi-IN 两个评测集，覆盖印地语与印度英语，其中印地语是该排行榜多语言板块首个非欧洲语言。数据集含公开与私有分割，共 4,888 位说话人，并记录 12 项说话人属性。",
    reason:"把评测单元从单一 WER 下探到带 12 项说话人属性的分组，能暴露模型在不同地域、口音、设备上的表现差异，让 ASR 选型不再只看平均错误率。",
    source:"Hugging Face：Blog", url:"https://huggingface.co/blog" },

  // ===== 行业动态 =====
  { cat:"industry", no:8, time:"8月29日 09:47",
    title:"OpenAI 终止与 Cursor 合作，11 月 12 日生效",
    summary:"OpenAI 因 SpaceX 收购 Cursor 后信任问题，决定终止向其提供模型访问，合作于 11 月 12 日结束。开发者仍可通过自有 OpenAI API 密钥及 IDE 扩展继续使用 GPT 模型。",
    reason:"终止合作把信任作为前提，依赖 Cursor 内嵌 OpenAI 模型的团队将需要在 11 月 12 日前重新确认编码工作流的模型访问路径。",
    source:"X：Tibo", url:"https://x.com/thsottiaux" },
  { cat:"industry", no:9, time:"8月29日 08:01",
    title:"OpenAI 与泰国高教部推出八周加速器，支持泰国 AI 初创企业",
    summary:"OpenAI 与泰国高等教育、科研与创新部（MHESI）在曼谷宣布启动 OpenAI x MHESI AI Accelerator，为期八周，首批遴选 10 家聚焦医疗、健康与教育的初创公司。每家团队将获得 2,000 美元 API 额度、一对一技术指导及 OpenAI 最新前沿模型访问权。",
    reason:"这是 OpenAI 与泰国政府的首个公私合作项目，旨在帮助初创企业将原型推进至可部署产品。",
    source:"OpenAI：官网动态", url:"https://openai.com/news" },
  { cat:"industry", no:10, time:"8月29日 02:07",
    title:"联邦法官裁定特朗普政府将 Anthropic 列入黑名单违法",
    summary:"美国加州北区联邦地区法院法官 Rita Lin 裁定，特朗普政府将 Anthropic 列为国家安全供应链风险并禁止其 AI 技术使用的行为违法，构成违反第一修正案的非法报复。法院批准了 Anthropic 部分即决判决动议。",
    reason:"裁定将政府拉黑定性为对 Anthropic 拒绝放宽致命自主武器与大规模监控限制的报复，为 AI 公司以安全承诺对抗强制采购压力提供可援引判例。",
    source:"Ars Technica：AI", url:"https://arstechnica.com/ai/" },
  { cat:"industry", no:11, time:"8月28日 14:00",
    title:"OpenAI 决定终止向 Cursor 提供模型，因 SpaceX 收购后合规风险",
    summary:"OpenAI 已通知 SpaceX，将终止向 Cursor 提供 OpenAI 模型的合同，拟定关停日期为 2026 年 11 月 12 日，并给予合同允许的最长通知期。OpenAI 称此举源于无法确信 SpaceX 会遵守服务条款。",
    reason:"OpenAI 把合同终止与收购后的控制权变更挂钩，11 月 12 日的关闭日期将直接改变 Cursor 开发者对模型替代和迁移窗口的规划。",
    source:"OpenAI：官网动态", url:"https://openai.com/news" },

  // ===== 论文研究 =====
  { cat:"paper", no:12, time:"8月29日 08:01",
    title:"Infer-forge：围绕 SGLang 的 Harness、Loop 与 Graph 工程",
    summary:"Infer-forge 是一套围绕 SGLang 推理优化的内部工程系统，通过 MonoRepo、Harness、Task Loop 与 Task Graph 四种结构，将部署点约束链（模型、SLO、拓扑、运行时、加速平台）转化为可复现、可审计的工程流程。",
    reason:"把推理部署从「手工调参」变成可复现工程流程，对大规模模型服务团队极具参考价值。",
    source:"LMSYS：Blog", url:"https://lmsys.org/blog/" },
  { cat:"paper", no:13, time:"8月29日 08:01",
    title:"LLM 并非（始终）符合贝叶斯：量化 LLM 概率信念的内部（不）一致性",
    summary:"苹果机器学习研究团队提出一种新方法，将 LLM 视为信息处理规则，利用其与贝叶斯更新的信息处理差距，研究模型如何根据证据更新概率信念的内部（不）一致性。实验评估了 LLM 在医学、科学、法律等复杂领域的信念更新表现。",
    reason:"揭示 LLM 概率推理与贝叶斯理想之间的系统性偏差，有助于设计更可靠的不确定性估计与校准方法。",
    source:"Apple Machine Learning Research", url:"https://machinelearning.apple.com/" },
  { cat:"paper", no:14, time:"8月29日 08:01",
    title:"Agent Seer：从工具规格理解中合成评测场景",
    summary:"Agent Seer 提出一种无需人工构建或实时执行工具即可合成评测场景的方法，利用函数名、自然语言描述和类型化参数模式等工具规格中的语义信息，生成能反映从业者组合工具与多轮迭代的真实测试场景。",
    reason:"解决手工构建场景依赖领域专家、难以跨工具生态扩展且静态基准无法跟踪 API 演进的问题。",
    source:"Apple Machine Learning Research", url:"https://machinelearning.apple.com/" },
  { cat:"paper", no:15, time:"8月29日 01:25",
    title:"Anthropic 让 Claude 自主训练模型以缓解对齐失败",
    summary:"Anthropic 探索让 Claude 自主训练模型的新范式，试图通过模型自我监督与迭代反馈来缓解对齐失败（alignment failure）问题，减少人类标注瓶颈。",
    reason:"对齐失败是 LLM 安全核心难题之一，模型自主训练若能保持可控，将改变 RLHF 与可扩展监督的游戏规则。",
    source:"Anthropic Research", url:"https://www.anthropic.com/research" },

  // ===== 技巧与观点（含 GitHub AI 趋势） =====
  { cat:"tip", no:16, time:"本周",
    title:"GitHub 热门：openclaw/openclaw —— 跨平台个人 AI 助手",
    summary:"Your own personal AI assistant. Any OS. Any Platform. The lobster way. 🦞 —— 一个旨在成为个人跨平台 AI 助手的开源项目，本周位列 GitHub AI 趋势榜第一。",
    reason:"个人 AI 助手 + 跨平台是 2026 年最热的应用方向之一，适合学习 Agent 与工具调用架构。",
    source:"GitHub", url:"https://github.com/openclaw/openclaw" },
  { cat:"tip", no:17, time:"本周",
    title:"GitHub 热门：deepseek-ai/deepseek-harness —— 插件化 AI 评测",
    summary:"DeepSeek Harness: Everything is a Plugin. 将模型评测抽象为插件体系，便于快速接入新任务、新指标与新模型。",
    reason:"插件化评测框架是模型迭代基础设施，理解它有助于搭建自己的模型评估流水线。",
    source:"GitHub", url:"https://github.com/deepseek-ai/deepseek-harness" },
  { cat:"tip", no:18, time:"本周",
    title:"GitHub 热门：n8n-io/n8n —— 原生 AI 能力的工作流自动化",
    summary:"Fair-code workflow automation platform with native AI capabilities. 通过可视化节点编排，把 LLM、API、数据库连接成自动化流程。",
    reason:"低代码/无代码 AI 工作流是 Agent 落地的主流形态之一，适合快速搭建 MVP。",
    source:"GitHub", url:"https://github.com/n8n-io/n8n" },
  { cat:"tip", no:19, time:"本周",
    title:"GitHub 热门：Significant-Gravitas/AutoGPT —— 自主 Agent 经典项目",
    summary:"AutoGPT 是「人人可用的 AI」愿景的代表项目，让大模型自主拆解目标、调用工具并迭代执行。",
    reason:"学习 Agent 规划、记忆与工具调用的必读项目，代码与社区文档都很丰富。",
    source:"GitHub", url:"https://github.com/Significant-Gravitas/AutoGPT" },
  { cat:"tip", no:20, time:"本周",
    title:"GitHub 热门：langgenius/dify —— 构建 Agentic 工作流与 RAG",
    summary:"Build Agentic workflows, RAG pipelines, with rich AI model and tool support. Dify 提供完整的 LLM 应用开发平台，从 Prompt 管理到 RAG 再到 Agent 编排。",
    reason:"一站式 LLM 应用平台，适合把学到的 RAG、Prompt、Agent 知识快速变成可演示产品。",
    source:"GitHub", url:"https://github.com/langgenius/dify" },
  { cat:"tip", no:21, time:"本周",
    title:"GitHub 热门：microsoft/generative-ai-for-beginners —— 生成式 AI 入门课",
    summary:"21 Lessons, Get Started Building with Generative AI. 微软开源的生成式 AI 入门课程，覆盖从 Prompt 到 RAG、Fine-tuning 的完整路径。",
    reason:"系统学习生成式 AI 的免费优质资源，可作为本站 AI 知识板块的延伸阅读。",
    source:"GitHub", url:"https://github.com/microsoft/generative-ai-for-beginners" }
];
