// 自我审核题库：type = 'single'(单选) | 'tf'(判断)
// 单选 answer 为选项下标(0 起)；判断 answer 为布尔 true/false
// 每个方向 15 题，打乱后按「每 10 题一组」练习，会话内不重复。
const QUIZZES = {
  python: [
    { type:"single", q:"Python 中用于定义函数的关键字是？", options:["def","func","function","define"], answer:0,
      explain:"Python 用 def 定义函数，例如 def add(a,b): return a+b。" },
    { type:"tf", q:"Python 的列表(list)是有序且可修改的数据结构。", answer:true,
      explain:"list 用 [] 定义，有序、可变，支持增删改和索引访问。" },
    { type:"single", q:"以下哪个不是 Python 的基本数据类型？", options:["int","float","str","array"], answer:3,
      explain:"array 不是内置基础类型，数组常用 list 或 numpy.array。内置类型有 int/float/str/bool 等。" },
    { type:"tf", q:"Python 中变量使用前必须先声明类型。", answer:false,
      explain:"Python 是动态类型语言，赋值即定义，无需声明类型。" },
    { type:"single", q:"用于捕获异常的关键字组合是？", options:["try/except","if/else","do/catch","check/error"], answer:0,
      explain:"用 try...except 捕获运行期异常，避免程序崩溃。" },
    { type:"single", q:"执行 nums = [0,1,2,3,4,5] 后，nums[1:4] 的结果是？", options:["[1,2,3]","[0,1,2, 3]","[1,2,3,4]","[2,3,4]"], answer:0,
      explain:"切片 [1:4] 包含索引 1、2、3，不包含 4，结果是 [1,2,3]。" },
    { type:"tf", q:"Python 中字典的键(key)必须是不可变类型。", answer:true,
      explain:"字典用哈希表实现，键必须可哈希（不可变），如字符串、数字、元组；列表不能当键。" },
    { type:"single", q:"lambda 表达式主要用于创建？", options:["匿名函数","类","模块","异常"], answer:0,
      explain:"lambda 用于创建一行匿名函数，如 lambda x: x*2。" },
    { type:"tf", q:"Python 中的字符串(str)是不可变对象。", answer:true,
      explain:"字符串不可变，修改会生成新对象；可用 replace() 等返回新字符串。" },
    { type:"single", q:"类(class)中 __init__ 方法的作用是？", options:["初始化对象属性","销毁对象","定义类变量","定义静态方法"], answer:0,
      explain:"__init__ 是构造方法，在创建对象时自动调用，用于初始化属性。" },
    { type:"single", q:"列表推导式 [x*2 for x in range(5)] 的结果是？", options:["[0,2,4,6,8]","[1,2,3,4,5]","[0,1,2,3,4]","[2,4,6,8,10]"], answer:0,
      explain:"range(5) 是 0~4，逐个乘 2 得到 [0,2,4,6,8]。" },
    { type:"tf", q:"Python 是解释型语言，代码逐行执行，无需先编译成机器码。", answer:true,
      explain:"Python 由解释器逐行执行（CPython 会先编译为字节码，但无需手动编译链接）。" },
    { type:"single", q:"读取文本文件并一次性返回全部内容，应调用？", options:["f.read()","f.readlines() 返回列表","两者都行","f.open()"], answer:2,
      explain:"f.read() 返回整个字符串；f.readlines() 返回按行拆分的列表，二者都能拿到全部内容。" },
    { type:"single", q:"用 set([1,1,2,3,3]) 得到的结果是？", options:["{1,2,3}","[1,1,2,3,3]","{1,1,2,3,3}","报错"], answer:0,
      explain:"集合(set)会自动去重，重复元素被合并，结果是 {1,2,3}。" },
    { type:"tf", q:"在 Python 中用 import 可以引入标准库或第三方模块。", answer:true,
      explain:"import math / import pandas 等用于引入模块，是代码复用与扩展的核心机制。" }
  ],
  mysql: [
    { type:"single", q:"SQL 中用于从一个或多个表中查询数据的关键字是？", options:["GET","SELECT","FETCH","READ"], answer:1,
      explain:"SELECT 用于查询，如 SELECT * FROM user;" },
    { type:"tf", q:"INNER JOIN 会保留左表和右表中所有不匹配的行。", answer:false,
      explain:"INNER JOIN 只保留两边都能匹配上的行；不匹配的会被丢弃。LEFT JOIN 才保留左表全部。" },
    { type:"single", q:"以下哪种约束能唯一标识表中的一行？", options:["NOT NULL","DEFAULT","PRIMARY KEY","CHECK"], answer: 2,
      explain:"PRIMARY KEY 主键唯一且非空，用来唯一标识一行记录。" },
    { type:"tf", q:"索引（Index）通常能加快 SELECT 查询速度，但会拖慢写入。", answer:true,
      explain:"索引让查询从全表扫描变目录查找，但插入/更新时要同步维护索引，写入变慢。" },
    { type:"single", q:"用于分组聚合统计的关键字是？", options:["GROUP BY","ORDER BY","LIMIT","WHERE"], answer:0,
      explain:"GROUP BY 分组后用 COUNT/SUM/AVG 等聚合函数汇总。" },
    { type:"single", q:"要删除表中所有数据但保留表结构，应该使用？", options:["DELETE FROM 表","DROP TABLE 表","TRUNCATE TABLE 表","REMOVE 表"], answer:2,
      explain:"TRUNCATE 清空全表数据且保留结构，速度通常比 DELETE 快。" },
    { type:"tf", q:"WHERE 子句可以直接对 GROUP BY 分组后的聚合结果进行过滤。", answer:false,
      explain:"WHERE 在分组前过滤行；分组后的聚合结果过滤要用 HAVING。" },
    { type:"single", q:"事务 ACID 特性中，A 指的是？", options:["Atomicity（原子性）","Availability（可用性）","Atomic（原子）","Accuracy（准确性）"], answer:0,
      explain:"ACID 中 A 是 Atomicity 原子性，指事务要么全成功要么全失败。" },
    { type:"tf", q:"在 SQL 中，NULL 与空字符串 '' 是同一个意思。", answer:false,
      explain:"NULL 表示「未知/无值」，空字符串是长度为 0 的字符串，二者不同。" },
    { type:"single", q:"LIMIT 10 OFFSET 20 表示？", options:["返回第 21~30 条","返回前 30 条","返回第 20~30 条","跳过前 10 条返回 20 条"], answer:0,
      explain:"OFFSET 20 跳过前 20 条，LIMIT 10 再取 10 条，即第 21~30 条。" },
    { type:"single", q:"想给每行编号（如 1,2,3…）而不改变原表，应使用？", options:["ROW_NUMBER()","COUNT(*)","RANK()","AUTO_INCREMENT"], answer:0,
      explain:"ROW_NUMBER() 是窗口函数，按指定顺序为结果集每行生成一个连续序号。" },
    { type:"single", q:"保证「一个表引用另一个表主键」的约束是？", options:["FOREIGN KEY","UNIQUE","INDEX","VIEW"], answer:0,
      explain:"外键(FOREIGN KEY)建立表间引用关系，保证引用完整性。" },
    { type:"tf", q:"第三范式(3NF)要求非主键字段不依赖其他非主键字段（消除传递依赖）。", answer:true,
      explain:"3NF 在 2NF 基础上消除传递依赖，减少冗余、避免更新异常。" },
    { type:"single", q:"想查看一条 SQL 的执行计划、判断是否走索引，应使用？", options:["EXPLAIN","DESCRIBE TABLE","SHOW STATUS","TRACE"], answer:0,
      explain:"EXPLAIN 输出执行计划，可看到是否使用索引、扫描行数等，是慢查询调优的利器。" },
    { type:"single", q:"MySQL 默认的事务隔离级别通常不包括以下哪项也可能导致的问题？", options:["脏读","不可重复读","幻读","数据加密"], answer:3,
      explain:"隔离级别讨论的是脏读/不可重复读/幻读；数据加密属于安全范畴，不是隔离级别的话题。" }
  ],
  data: [
    { type:"single", q:"pandas 中二维带列名的数据结构叫什么？", options:["Series","DataFrame","array","dict"], answer:1,
      explain:"DataFrame 是带行索引和列名的二维表格，是 pandas 分析的核心对象。" },
    { type:"tf", q:"数据分析中应该先收集数据，再明确要回答的业务问题。", answer:false,
      explain:"正确流程是先明确问题，再找数据、清洗、分析，避免为分析而分析。" },
    { type:"single", q:"处理缺失值常用的 pandas 方法是？", options:["dropna()","fillna()","两者都是","delete()"], answer:2,
      explain:"dropna 删除缺失行/列，fillna 用均值等填充，都是常见手段。" },
    { type:"tf", q:"相关系数高就意味着两个变量存在因果关系。", answer:false,
      explain:"相关不等于因果，高相关可能只是巧合或受第三方变量影响，需谨慎下结论。" },
    { type:"single", q:"模型评估中，衡量『预测正例中真正为正的比例』的指标是？", options:["准确率","精确率(Precision)","召回率(Recall)","F1"], answer:1,
      explain:"精确率=TP/(TP+FP)，关注预测为正的样本有多准；召回率关注真正例被找出了多少。" },
    { type:"single", q:"df.shape 返回的是什么？", options:["行数、列数","列名","索引","数据类型"], answer:0,
      explain:"df.shape 返回元组 (行数, 列数)，例如 (1000, 5)。" },
    { type:"tf", q:"箱线图(boxplot)适合查看数据的分布、中位数和异常值。", answer:true,
      explain:"箱线图能展示中位数、四分位数、whisker 与异常点，是分布诊断的利器。" },
    { type:"single", q:"将不同量纲特征缩放到相近尺度的常用方法是？", options:["标准化/归一化","one-hot 编码","降维","交叉验证"], answer:0,
      explain:"标准化（Z-score）或归一化（Min-Max）让不同特征尺度可比，提升模型稳定性。" },
    { type:"tf", q:"划分训练集和测试集时，通常需要随机打乱数据。", answer:true,
      explain:"随机划分能减少数据顺序带来的偏差，更真实反映模型泛化能力。" },
    { type:"single", q:"AUC 指标主要用于评估？", options:["分类模型的排序/区分能力","回归模型的均方误差","聚类效果","特征重要性"], answer:0,
      explain:"AUC（ROC 曲线下面积）衡量模型把正例排在负例前面的能力，值越接近 1 越好。" },
    { type:"single", q:"用 Python 画折线图最常用的轻量库是？", options:["Matplotlib / Seaborn","Photoshop","Excel 自带","Word"], answer:0,
      explain:"Matplotlib（及 Seaborn）是 Python 数据可视化的事实标准，可画折线/柱状/散点等。" },
    { type:"single", q:"判断『数据集中某列缺失值占比』可以调用？", options:["df.isnull().mean()","df.count()","df.describe()","df.info()"], answer:0,
      explain:"df.isnull().mean() 按列返回缺失比例（0~1），快速定位缺失严重的字段。" },
    { type:"tf", q:"线性回归假设自变量与因变量之间存在线性关系。", answer:true,
      explain:"线性回归用一条（或多条）直线拟合 y = w·x + b，假设特征与目标是线性关系。" },
    { type:"single", q:"无监督学习中，不需要标注标签的典型任务是？", options:["聚类","分类","回归","预测"], answer:0,
      explain:"聚类(KMeans 等)在没有任何标签的情况下把相似样本聚成簇，属于无监督。" },
    { type:"tf", q:"特征工程（特征构造/选择/缩放）往往比模型选择更能决定分析效果。", answer:true,
      explain:"『数据决定上限，模型逼近上限』，特征工程直接影响模型能学到什么，常是关键。" }
  ],
  ai: [
    { type:"single", q:"RAG（检索增强生成）的核心思想是？", options:["让模型凭记忆生成","先检索相关资料再生成","对模型做全量微调","用更大数据集预训练"], answer:1,
      explain:"RAG 先检索外部知识库，再把资料注入 Prompt 让模型生成，能显著减少幻觉。" },
    { type:"tf", q:"大模型（LLM）的输出是基于概率生成，可能产生看似合理但错误的内容（幻觉）。", answer:true,
      explain:"LLM 按概率逐 token 生成，不会严格『查事实』，因此会自信地胡说，需要验证。" },
    { type:"single", q:"LoRA 属于以下哪类技术？", options:["提示工程","参数高效微调(PEFT)","数据增强","模型蒸馏"], answer:1,
      explain:"LoRA 是 PEFT 的一种，只训练少量低秩适配参数，显存占用低、微调高效。" },
    { type:"tf", q:"Transformer 架构的核心机制是自注意力(Self-Attention)。", answer:true,
      explain:"Self-Attention 让每个 token 关注序列中相关的其他 token，是现代 LLM 的基石。" },
    { type:"single", q:"2026 年 Agent 落地的关键进阶概念『上下文工程』主要解决什么？", options:["让模型参数量更大","系统地为 Agent 提供正确的知识/工具/记忆/结构","替代所有提示词","训练更快"], answer:1,
      explain:"Context Engineering 强调给 Agent 喂对的知识、工具、结构与记忆（skills/MCP/子代理），是提示工程的进阶。" },
    { type:"single", q:"Embedding 的主要作用是把文本/图片等变成？", options:["固定长度的向量","关键词列表","数据库表","Prompt 模板"], answer:0,
      explain:"Embedding 把离散对象编码成稠密向量，语义相近的向量距离也相近，是 RAG 检索的基础。" },
    { type:"tf", q:"对于所有私有知识问答场景，直接微调大模型总是比 RAG 更省成本。", answer:false,
      explain:"多数情况下 R,AG 更经济、易更新、可溯源；微调适合改变模型风格或掌握特定格式。" },
    { type:"single", q:"一个典型的 AI Agent 通常由哪几部分组成？", options:["模型 + 工具 + 记忆 + 规划","模型 + 数据库","提示词 + 界面","GPU + 数据集"], answer:0,
      explain:"Agent = 大模型（大脑）+ 工具（手脚）+ 记忆（上下文）+ 规划（决策）。" },
    { type:"tf", q:"GPT 系列模型属于生成式 AI(Generative AI)。", answer:true,
      explain:"GPT 通过生成文本/代码等内容工作，是典型的生成式 AI。" },
    { type:"single", q:"想在本地私有化部署开源大模型，最常用的工具之一是？", options:["Ollama","Photoshop","Excel","Postman"], answer:0,
      explain:"Ollama 可在本地一键运行 Qwen、Llama 等开源模型，数据不出本机。" },
    { type:"single", q:"奠定 Transformer 的论文《Attention Is All You Need》发布于哪一年？", options:["2017","2019","2021","2023"], answer:0,
      explain:"2017 年 Google 提出 Transformer，彻底改变了 NLP 与后续大模型的发展。" },
    { type:"single", q:"RAG 检索阶段通常把查询和文档都转成向量后用什么方式匹配？", options:["向量相似度（如余弦）","关键词精确匹配","随机采样","哈希"], answer:0,
      explain:"向量数据库用余弦/内积相似度找到与查询最相近的文档块，再喂给大模型。" },
    { type:"tf", q:"多模态模型（如能看图说话的模型）可以同时处理文本、图像等多种输入。", answer:true,
      explain:"多模态让模型跨文本/图像/音频等模态理解与生成，是 2025–2026 的热门方向。" },
    { type:"single", q:"提示词中的『少样本(few-shot)』是指？", options:["在 Prompt 里给几个示例","把模型参数量减少","减少生成长度","只用一条指令"], answer:0,
      explain:"few-shot 通过在提示中提供示例，让模型更快理解任务格式与期望输出。" },
    { type:"tf", q:"推理(Inference)阶段优化（KV Cache、量化、蒸馏）主要是为了降低延迟与成本。", answer:true,
      explain:"量化/蒸馏/KV Cache 等手段能在尽量保效果的前提下，让大模型更快、更省地服务。" }
  ]
};
